services:
  postgres:
    image: postgres:15
    container_name: postgres-heroes
    environment:
      POSTGRES_DB: heroes
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'pg_data:/var/lib/postgresql/data'
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - '9000:9000'
      - '9090:9090'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9090"
    volumes:
      - 'minio_data:/data'
volumes:
  pg_data:
  minio_data:
