export enum Superpower {
  FLIGHT = 'flight',
  SUPER_STRENGTH = 'super_strength',
  INVISIBILITY = 'invisibility',
  TELEPATHY = 'telepathy',
  TELEKINESIS = 'telekinesis',
  SUPER_SPEED = 'super_speed',
  X_RAY_VISION = 'x_ray_vision',
  HEAT_VISION = 'heat_vision',
  INVULNERABILITY = 'invulnerability',
  SHAPE_SHIFTING = 'shape_shifting',
  TIME_MANIPULATION = 'time_manipulation',
  ELEMENTAL_CONTROL = 'elemental_control',
  MIND_CONTROL = 'mind_control',
  HEALING = 'healing',
  ENHANCED_SENSES = 'enhanced_senses',
  ENERGY_PROJECTION = 'energy_projection',
  WALL_CRAWLING = 'wall_crawling',
  WEATHER_CONTROL = 'weather_control',
  MAGNETISM = 'magnetism',
  TECHNOPATHY = 'technopathy',
}

export const SuperpowerLabels: Record<Superpower, string> = {
  [Superpower.FLIGHT]: 'Політ',
  [Superpower.SUPER_STRENGTH]: 'Надлюдська сила',
  [Superpower.INVISIBILITY]: 'Невидимість',
  [Superpower.TELEPATHY]: 'Телепатія',
  [Superpower.TELEKINESIS]: 'Телекінез',
  [Superpower.SUPER_SPEED]: 'Надшвидкість',
  [Superpower.X_RAY_VISION]: 'Рентгенівське зір',
  [Superpower.HEAT_VISION]: 'Теплове зір',
  [Superpower.INVULNERABILITY]: 'Невразливість',
  [Superpower.SHAPE_SHIFTING]: 'Зміна форми',
  [Superpower.TIME_MANIPULATION]: 'Маніпуляція часом',
  [Superpower.ELEMENTAL_CONTROL]: 'Контроль стихій',
  [Superpower.MIND_CONTROL]: 'Контроль розуму',
  [Superpower.HEALING]: 'Зцілення',
  [Superpower.ENHANCED_SENSES]: 'Посилені почуття',
  [Superpower.ENERGY_PROJECTION]: 'Проекція енергії',
  [Superpower.WALL_CRAWLING]: 'Повзання по стінах',
  [Superpower.WEATHER_CONTROL]: 'Контроль погоди',
  [Superpower.MAGNETISM]: 'Магнетизм',
  [Superpower.TECHNOPATHY]: 'Технопатія',
};
